[package]
name = "clash-verge-service"
version = "0.1.0"
edition = "2021"
authors = ["stallr"]
license = "GPL-3.0"
repository = "https://github.com/stallr/clash-verge-service.git"

[[bin]]
name = "clash-verge-service"
path = "src/main.rs"

[[bin]]
name = "install-service"
path = "src/install.rs"

[[bin]]
name = "uninstall-service"
path = "src/uninstall.rs"

[dependencies]
warp = "0.3"
anyhow = "1.0"
log = "0.4.20"
log4rs = "1.0.0"
once_cell = "1.14"
serde_json = "1.0"
parking_lot = "0.12.1"
windows-service = "0.6.0"
tokio = { version = "1.33.0", features = ["full"] }
serde = { version = "1.0.190", features = ["derive"] }

[target.'cfg(target_os = "linux")'.dependencies]
openssl ={ version = "0.10", features = ["vendored"] }

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "s"
